#!/bin/sh
# Exercises the documentation checker against deterministic synthetic Swift sources.
set -eu
LC_ALL=C
export LC_ALL

ROOT=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)
FIXTURE_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/codingbuddy-docstring-fixtures.XXXXXX")
trap 'rm -rf "$FIXTURE_ROOT"' EXIT HUP INT TERM

mkdir -p "$FIXTURE_ROOT/CodingBuddy" "$FIXTURE_ROOT/CodingBuddyTests"

cat > "$FIXTURE_ROOT/CodingBuddy/Fixture.swift" <<'SWIFT'
import SwiftUI

/// A fixture whose members exercise declaration and lexical-state tracking.
struct Fixture {
    /// A documented property separated from its declaration by an attribute.
    @MainActor
    let value: String

    /// Returns text containing tokens that must not affect scope tracking.
    func documented(
        value: String
    ) -> String {
        let normal = "{ // not a comment /* not a block */ }"
        let multiline = """
        } // still a string
        /* still a string { */
        /// not a documentation comment
        """
        let rawMultiline = #"""
        { /* raw string content */ // }
        """#
        return normal + multiline + rawMultiline + value
    }

    func undocumented(
        value: String
    ) -> String
    {
        /* An outer comment with a nested /* { comment } */ marker. */
        let local = value
        return local
    }

    /// Exercises a closure default without mistaking it for the function body.
    func guardedValue(
        beforeValidation: () -> Void = {},
        value: String
    ) -> String? {
        guard !value.isEmpty,
              let first = value.first
        else { return nil }
        beforeValidation()
        guard first.isLetter,
              let suffix = value.dropFirst().first
        else { return nil }
        return String(suffix)
    }

    var body: some View { EmptyView() }

    ///
    /// A meaningful line makes the contiguous documentation block count.
    let documentedAfterEmptyLine: String

    let storedBeforeCallable: String
    func callableAfterStoredProperty() {}

    init(
        loader: () -> String = {
            let localValue = "fixture"
            return localValue
        }
    ) {
        let localValue = loader()
        _ = localValue
    }
}

/// A protocol fixture.
protocol Worker {
    /// A documented multiline bodyless requirement.
    func work(
        value: String
    ) async throws -> String
}

/// An enum fixture.
enum Status {
    /// A documented case.
    case ready = "{ // literal content"
    case waiting = "} /* literal content */"
}
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/EmptyDocumentation.swift" <<'SWIFT'
///
struct EmptyDocumentationType {}
SWIFT

printf '%s\n' \
    '///   ' \
    'struct WhitespaceDocumentationType {}' \
    > "$FIXTURE_ROOT/CodingBuddy/WhitespaceDocumentation.swift"

cat > "$FIXTURE_ROOT/CodingBuddy/Generated.swift" <<'SWIFT'
// Copyright Fixture Authors.
// @generated
struct UndocumentedGeneratedType {}
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/InlineGeneratedMarker.swift" <<'SWIFT'
/* @generated */ struct InlineGeneratedMarkerType {}
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/StandaloneBlockGenerated.swift" <<'SWIFT'
/* @generated */
struct UndocumentedBlockGeneratedType {}
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/GeneratedProse.swift" <<'SWIFT'
// Generated by fixture builder. Do not edit.
struct UndocumentedProseType {}
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/GeneratedString.swift" <<'SWIFT'
let generatedMarkerInAString = "@generated"
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddy/LateGeneratedMarker.swift" <<'SWIFT'
struct UndocumentedBeforeMarkerType {}
// @generated
SWIFT

cat > "$FIXTURE_ROOT/CodingBuddyTests/CheckerTests.swift" <<'SWIFT'
struct UndocumentedTestType {}
SWIFT

JSON=$(
    "$ROOT/scripts/check-docstring-coverage.sh" \
        --source-root "$FIXTURE_ROOT" \
        --minimum 0 \
        --json
)
JSON_REPEAT=$(
    "$ROOT/scripts/check-docstring-coverage.sh" \
        --source-root "$FIXTURE_ROOT" \
        --minimum 0 \
        --json
)
[ "$JSON" = "$JSON_REPEAT" ] || {
    echo "error: repeated fixture scans produced different JSON" >&2
    exit 1
}

expect_json() {
    key=$1
    expected=$2
    if ! printf '%s\n' "$JSON" | grep -q "\"$key\":$expected\([,}]\)"; then
        echo "error: expected JSON field $key=$expected" >&2
        echo "$JSON" >&2
        exit 1
    fi
}

expect_json eligible 20
expect_json documented 9
expect_json missing 11
expect_json excluded_declarations 8
expect_json swiftui_body 1
expect_json local_declarations 7
expect_json test_files 1
expect_json generated_files 2
expect_json files_scanned 7
expect_json passed true
printf '%s\n' "$JSON" | grep -Fq '"test_files":["CodingBuddyTests/CheckerTests.swift"]'
printf '%s\n' "$JSON" | grep -Fq '"generated_files":["CodingBuddy/Generated.swift","CodingBuddy/StandaloneBlockGenerated.swift"]'

HUMAN=$(
    "$ROOT/scripts/check-docstring-coverage.sh" \
        --source-root "$FIXTURE_ROOT" \
        --minimum 0
)
printf '%s\n' "$HUMAN" | grep -Fq 'Excluded test files:'
printf '%s\n' "$HUMAN" | grep -Fq '  CodingBuddyTests/CheckerTests.swift'
printf '%s\n' "$HUMAN" | grep -Fq 'Excluded generated files:'
printf '%s\n' "$HUMAN" | grep -Fq '  CodingBuddy/Generated.swift'
printf '%s\n' "$HUMAN" | grep -Fq '  CodingBuddy/StandaloneBlockGenerated.swift'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/EmptyDocumentation.swift:2 (type)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/GeneratedProse.swift:2 (type)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/GeneratedString.swift:1 (property)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/InlineGeneratedMarker.swift:1 (type)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/LateGeneratedMarker.swift:1 (type)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/Fixture.swift:55 (property)'
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/Fixture.swift:56 (func)'
if printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/Fixture.swift:61 (property)'; then
    echo "error: default-argument closure local was reported as an API declaration" >&2
    exit 1
fi
if printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/Fixture.swift:66 (property)'; then
    echo "error: initializer-body local was reported as an API declaration" >&2
    exit 1
fi
printf '%s\n' "$HUMAN" | grep -Fq 'CodingBuddy/WhitespaceDocumentation.swift:2 (type)'

FAILURE_STDOUT="$FIXTURE_ROOT/threshold.json"
FAILURE_STDERR="$FIXTURE_ROOT/threshold.err"
if "$ROOT/scripts/check-docstring-coverage.sh" \
    --source-root "$FIXTURE_ROOT" \
        --minimum 46 \
    --json > "$FAILURE_STDOUT" 2> "$FAILURE_STDERR"; then
    echo "error: expected the 46 percent fixture threshold to fail" >&2
    exit 1
fi
grep -q '"coverage_percent":45.0' "$FAILURE_STDOUT"
grep -q '"passed":false' "$FAILURE_STDOUT"
grep -q 'below the required 46%' "$FAILURE_STDERR"

echo "Docstring coverage fixtures passed."
